### ISSUE TITLE
BayesianTargetEncoder can not be pickled

### ISSUE THREAD

**Issue by bhomass** [MaxHalford/xam#7] opened 2019-05-17 08:14 UTC
I tried pickle.dump the BayesianTargetEncoder after fit(), but get this error
AttributeError: Can't pickle local object 'BayesianTargetEncoder.fit.<locals>.<lambda>'

It is for sure a problem in deployment, if you can not store away a pre-trained encoder. Is this a known issue? Can we get a fix for it? Thanks

**Comment by MaxHalford** [comment] 2019-05-17 09:19
I just checked; it's because it's using a `lambda` function to store the posteriors. I'll get this fixed as soon as possible. Thanks for opening an issue!

**Comment by MaxHalford** [comment] 2019-05-21 09:32
@bhomass I just pushed a fix. It should be good :). Feel free to reopen this issue if the problem persists.

**Closed by MaxHalford** 2019-05-21 09:32 UTC

**Comment by bhomass** [comment] 2019-09-23 15:19
Hi, I really appreciate you solved the pickle problem. But there is a bug of some kind. When you dump and load the encoder, the recovered encoder produces different results on the same input data. Please investigate. I need to put this into production real soon. Thank you.

**Comment by MaxHalford** [comment] 2019-09-24 07:22
Hello. First of all, I'm not able to reproduce the bug, so I'm going to need you to share a reproducible example. Secondly, this library is just here "for fun", and is much too brittle to be used in production.

**Comment by bhomass** [comment] 2019-09-24 17:45
Hey, my bad. nothing wrong with pickle. 
I know its like a toy in some ways, but is the best out there, and good enough to use if taking care. thanks for the contribution.
